### ISSUE TITLE
solomon-rabbitMq模块的延迟实现是不是需要基于rabbimq延迟插件rabbitmq_delayed_message_exchange

### ISSUE THREAD

**Issue by fenfeiyunluo** [ZeroNing/solomon-parent#1]
作者你好， 看了你的项目分享深受启发， 最近我也在做一个延迟消息的功能， 看到项目中实现延迟是在消息头中加入“x-delay”， 确认一下是否需要rabbimq中间件安装延迟队列插件才能生效？受云服务供应商限制无法支持这个插件， 所以特地确认一下这个实现方案是否必须依赖延迟插件。期待回复

**Comment by ZeroNing** [comment]
> 作者你好， 看了你的项目分享深受启发，最近我也在做一个延迟消息的功能， 看见项目中实现延迟是消息头中加入“x-delay”，是否需要确认一下rabbimq中间件安装延迟队列插件才能生效？受云服务供应商限制无法支持这个插件， 所以特地确认一下这个实现方案是否必须依赖延迟插件。期待回复

是需要rabbitmq安装延迟插件才可以
