### ISSUE TITLE
发送sendAndReceive的情况，有没有涉及到？

### ISSUE THREAD

**Issue by Stranded-f1sh** [ZeroNing/solomon-parent#2]

**Comment by ZeroNing** [comment]
这个还没有涉及到，你需要用到吗？

**Comment by ZeroNing** [comment]
> _没有提供说明。_

你好，现在Rabbitmq已经支持了请求-回复模式了，代码在Rabbimq模块下的AbstractConsumer

**Comment by ZeroNing** [comment]
> _No description provided._

![1728613428985](https://github.com/user-attachments/assets/6df73b7f-01ff-4ef1-8c1e-b4b0d4ef9c7d)

**Comment by ZeroNing** [comment]
> > _No description provided._
> 
> ![1728613428985](https://private-user-images.githubusercontent.com/41049158/375604487-6df73b7f-01ff-4ef1-8c1e-b4b0d4ef9c7d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MTM3NDIsIm5iZiI6MTcyODYxMzQ0MiwicGF0aCI6Ii80MTA0OTE1OC8zNzU2MDQ0ODctNmRmNzNiN2YtMDFmZi00ZWYxLThjMWUtYjRiMGQ0ZWY5YzdkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDAyMjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlZTUyZTg1NWE1ZWVkMmUxNTYyZGE0MzA4NWIyMTNhNjRlOWVhNTg5Y2E0NmVmOWQxMThiNjRmOGQ1ODg5MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Pg7KLZZRToSKBHP2aCEzEULKNTJ9JW91vF3p1BF3NlA)

![image](https://github.com/user-attachments/assets/0dad4430-b767-4522-8b9f-03bf5742b316)

**Comment by Stranded-f1sh** [comment]
好的，谢谢

**Comment by ZeroNing** [comment]
> 好的，谢谢

麻烦给个赞赞，谢谢🙏

**Comment by Stranded-f1sh** [comment]
mqModel.setReplyTo好像设置什么值都一样，convertSendAndReceieve方法去掉setReplyTo也都不影响结果。并且发送端的RoutingKey必须跟消费端的queues设置一样才可以，不然会报错。至于消费者交换机和绑定键设置什么都不影响结果。 这方面资料不太好找，也不清楚本就应该是这样还是说是BUG？

**Comment by ZeroNing** [comment]
> 影响

我一会去测试一下，稍等下

**Comment by ZeroNing** [comment]
> mqModel.setReplyTo好像设置什么值都一样，convertSendAndReceieve方法去掉setReplyTo也都不影响结果。并且发送端的RoutingKey必须跟消费端的queues设置一样才可以，不然会报错。至于消费者交换机和绑定键设置什么都不影响结果。 这方面资料不太好找，也不清楚本就应该是这样还是说是BUG？

 RabbitMQ 中，replyTo 属性用于指示响应应该发送到哪个队列。尽管你在消息属性中设置了 replyTo 为 test1，这并不会影响消息最初的路由。消息最初的路由是根据你发送的 routingKey 和交换机的绑定来决定的。

关键概念和流程

消息发送:

你发送消息到交换机 test，使用 routingKey 为 test。这个消息会根据交换机和绑定键路由到队列 test。
消息接收:

你的消费者订阅了队列 test，因此会接收到这条消息。
replyTo 属性:

replyTo 属性不会影响消息的初始路由过程。它仅在消息处理完毕后，如果需要发送响应时，指示应该将响应发送到哪个队列。
具体地，当消费者处理完消息后，如果需要发送响应，消费者会查看消息的 replyTo 属性，并将响应发送到指定的队列 test1。

总结

你的消费者订阅了 test 队列，因此会接收到所有发送到 test 队列的消息。
replyTo 属性并不会影响消息的初始路由，而是用于指示消费者在处理完消息后将响应发送到哪个队列。
在示例中，消息发送到交换机 test，使用 routingKey 为 test，因此消息会路由到队列 test。
消费者从 test 队列中接收消息后，可以通过 replyTo 属性将响应发送到队列 test1。
这样，你就能理解为什么设置 replyTo 为 test1 不会影响消息的初始接收，而是影响消息处理后的响应路由。

**Comment by ZeroNing** [comment]
> mqModel.setReplyTo好像设置什么值都一样，convertSendAndReceieve方法去掉setReplyTo也都不影响结果。并且发送端的RoutingKey必须跟消费端的queues设置一样才可以，不然会报错。至于消费者交换机和绑定键设置什么都不影响结果。 这方面资料不太好找，也不清楚本就应该是这样还是说是BUG？

而且发送routingKey是必须跟消费端的routingKey一致，才会消费成功，消费成功后，会通过AbstractConsumer中判断是否会有messageProperties.getReplyTo()，然后里面这个属性是一个这个值（amq.rabbitmq.reply-to.g1h2AA9yZXBseUAxMTkxNDIwNjUAAANDAAAAAGcMasc=.igKpB7EMmnx6dL2Py3sErA==）这个就属于是 RabbitMQ 自动生成的一个特殊队列名称，然后根据CorrelationId匹配，然后回应给到接口返回那里

**Comment by ZeroNing** [comment]
> mqModel.setReplyTo好像设置什么值都一样，convertSendAndReceieve方法去掉setReplyTo也都不影响结果。并且发送端的RoutingKey必须跟消费端的queues设置一样才可以，不然会报错。至于消费者交换机和绑定键设置什么都不影响结果。 这方面资料不太好找，也不清楚本就应该是这样还是说是BUG？

            if (ValidateUtils.isNotEmpty(this.messageProperties.getReplyTo())) {
                MessageProperties replyMessageProperties = new MessageProperties();
                replyMessageProperties.setCorrelationId(this.messageProperties.getCorrelationId());
                Message replyMessage = MessageBuilder.withBody(result.toString().getBytes()).andProperties(replyMessageProperties).build();
                this.rabbitUtils.sendReplyTo(this.messageProperties.getReplyTo(), replyMessage);
            }
这个就是AbstractConsumer请求回应的处理代码

**Comment by Stranded-f1sh** [comment]
受教了，谢谢！
